microsoft/botframework-sdk

- Builder/Node/guides/core-concepts.md
Updated the publish code example from TextBot to BotConnectorBot as metnioned in #13
> Updated publish code example

- CSharp/Samples/AnnotatedSandwichBot/AnnotatedSandwich.cs
In the samples, it is not clear how to process the form data once it is completed. Hence added that to AnnotatedSandwich sample.
> Added functionality to process the order once user completes the form

- Node/examples/todoBot/README.md
Hi there, I was going through the guide and found myself copying and pasting the links into a new tab. Thought turning them into clickable links would make everyone's life a tiny bit easier.
Thanks for open sourcing this! :beers:
> [readme] make links clickable

- README.md
Added the official Gitter chat room to the README.md
> Add Gitter Chat Room to Readme

- CSharp/Tests/Microsoft.Bot.Builder.Tests/PromptTests.cs
Test cases for the changes made in PR #71
> Added test cases for PromptConfirm case insensitive messages

- CSharp/Samples/README.md
is just something I found useful while reding the readme file a direct way of getting to the actual sample
> Links to the samples in the readme file

- Node/src/botbuilder.d.ts
> small spelling error

- CSharp/Tests/Microsoft.Bot.Sample.Tests/AlarmBotTests.cs
Additionally resolving of Start Time entity is fixed
> Fix for test failed if date & time format is not en-US

- Node/src/botbuilder.d.ts
Just reading the source, never mind...
> fix typo: should be , instead of .

- Node/examples/demo-facebook/app.js
set BOTFRAMEWORK_APPID and BOTFRAMEWORK_APPSECRET
https://github.com/Microsoft/BotBuilder/issues/398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/botbuilder/401)
> update demo-facebook commwent to env variables

- Node/examples/demo-facebook/app.js
http://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/botbuilder/409)
> Change "port" to "PORT" fix deploy to Heroku

- CSharp/Library/Dialogs/LuisDialog.cs
That was pretty useful, but it was missed after implementation of support of multiple LUIS service instances.
In case you want to reject this PR, before that please let me know what should I fix to get it merged, thank you.
> Ability to override calculation of the best intent is restored

- Node/src/botbuilder.d.ts
Fixed following issue :-)
https://github.com/Microsoft/BotBuilder/issues/552
> fix the property name of the Session class

- Node/src/Message.ts
the loop used 1 instead of the iterator var
> Single character fix for Message.composePrompt

- CSharp/Documentation/Attachments.cs
- CSharp/Documentation/Routing.cs
Update several places where sample code should have been of type "cs" and fix a few more typos.
> Fix additional typos and style issues

- CSharp/Documentation/Routing.cs
Update to use the async version of the SendToConversation method since the samples are awaiting that call
> Update Routing docs to use SendToConversationAsync method

- CSharp/Library/Microsoft.Bot.Builder.csproj
- CSharp/Library/MultilingualResources/Microsoft.Bot.Builder.de-DE.xlf
- CSharp/Library/Resource/Resources.de-DE.resx
Hello.
I'm creating a german chat bot using the microsoft bot framework.
So I tought it would be useful if I translated the messages into german.
> Add german translation

- en-us/bot-framework-overview.md
Bot directory is already available on https://bots.botframework.com/ and featured not only those from MS Build 2016.
> Update bot-framework-overview.md: remove "coming soon" on Bot Directory header

- Node/core/src/Channel.ts
Add two missing values to the list of possible channels.
Fixes #1586
> Add "directline" and "console" channels

- Node/core/src/bots/ChatConnector.ts
remove the extra comma at line 124
> remove the extra comma

- Node/core/src/bots/ChatConnector.ts
> format the code

- CSharp/Library/FormFlow/FormBuilder.cs
> Improve Localization Error Debugging

- Node/core/lib/botbuilder.d.ts
- Node/core/src/botbuilder.d.ts
> Exposing the protected session object in keyboard class to allow for cards extension

- Node/core/lib/dialogs/IntentDialog.js
- Node/core/src/dialogs/IntentDialog.ts
- Node/core/tests/Dialogs.js
> Fixing onBegin recognizeMode bug

- Node/core/src/locale/pt/BotBuilder.json
- Node/core/src/locale/pt/index.json
Hi Microsoft Team,
Just adding locale files for (PT) Portuguese language.
Cheers, Saverio.
> New locale (PT - Portuguese) for NodeJs BotBuilder

- issue_template.md
Provide users with more comprehensive instructions for reporting new issues, including link to Gitter group
> Create New Issue Template

- CSharp/Library/Microsoft.Bot.Builder/Dialogs/IDialogContext.cs
- CSharp/Tests/Microsoft.Bot.Builder.Tests/BotTests.cs
- CSharp/Tests/Microsoft.Bot.Builder.Tests/DialogTestBase.cs
Some things to provide feedback on:
- Location of the MessageOptions class
- Location of the unit tests for the SayAsync extension method
> [C# SDK] Add SayAsync extension method

- CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs
- CSharp/Tests/Microsoft.Bot.Builder.Tests/BotTests.cs
This PR depends on #2636. Please merge that one first!
> [C# SDK] Update PromptConfirm to internally use a PromptChoice

- .github/issue_template.md
Partially address https://github.com/Microsoft/BotBuilder/issues/2658
> Update issue template to remove #

- Node/core/README.md
Fix for #2552 update broken docs link in BotBuilder/Node/core/README.md
> [Node SDK] Fix for #2552 update broken docs link in BotBuilder/Node/core/README.md

- Node/calling/README.md
Just fixed the sample nodejs code to use the UniversalBot Connector and Dialog at root / to respond with Hello world on a message
> [Node SDK] fixed the Sample code to use the UniversalBot Connector 

- CSharp/Library/Microsoft.Bot.Connector.Shared/AttachmentEx.cs
- CSharp/Library/Microsoft.Bot.Connector.Shared/Microsoft.Bot.Connector.Common.csproj
- CSharp/Samples/SimpleDispatchDialog/SimpleDispatchDialog.cs
Other types on Activity already implement this interface.
> [C# SDK] Add IEquatable to Attachment and Do not respond to Ping in SimpleDispatchDialog sample

- CSharp/Library/Microsoft.Bot.Connector.NetCore/Content/Microsoft.Bot.Connector.NetCore.XML
- CSharp/Library/Microsoft.Bot.Connector.NetFramework/Content/Microsoft.Bot.Connector.xml
- CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs
> [C# SDK] Fixed the stack overflow issue with extension methods of IMessageActivity

- Node/core/lib/locale/fr/BotBuilder.json
Added localised numbers, ordinals and a couple of reverse_ordinals for /fr
> [Node SDK]  Add French localisation default phrases

- Node/examples/feature-onEnabled/app.js
Created example for [**IntentRecognizer.onEnabled()**](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/botbuilder.d.ts#L3547).
> [Node SDK] add feature-onEnabled() example

- Node/core/lib/dialogs/ActionSet.js
- Node/core/src/dialogs/ActionSet.ts
- Node/core/tests/actions.js
> [Node SDK] Fix on ActionSet.addDialogTrigger

- Node/core/lib/botbuilder.d.ts
Fixes for typos and grammar errors encountered while browsing reference documentation.
> [Node SDK] Fix typos and grammar errors

- Node/core/lib/dialogs/LuisRecognizer.js
- Node/core/src/dialogs/IntentRecognizer.ts
- Node/core/src/dialogs/LuisRecognizer.ts
- Node/examples/feature-onEnabled/app.js
- Node/examples/feature-onFilter/app.js
- Node/examples/feature-onFilter/onFilter_Example.json
- add `.onFilter()` example along with its LUIS model
- add `compositeEntities` to `.onRecognize()` and `IIntentRecognizerResult`
> [Node SDK] add .onFilter() example, add compositeEntities to .onRecognize()

- Node/core/lib/dialogs/PromptChoice.js
- Node/core/src/dialogs/PromptChoice.ts
Addresses Issue #2880:  **Prompts.choice # retry prompt - shows retry message but does not prompt choices again**
> [Node SDK] fix typos and choices not showing when reprompting users when using PromptChoice

- CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
- CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.nuspec
- CSharp/Library/Microsoft.Bot.Builder/MultilingualResources/Microsoft.Bot.Builder.pt-BR.xlf
- CSharp/Library/Microsoft.Bot.Builder/Resource/Resources.pt-BR.resx
- CSharp/Tests/Microsoft.Bot.Builder.Tests/FormTests.cs
* Added Brazilian Portuguese locale files for .Net BotBuilder.
> [.NET] Add Brazilian Portuguese (pt-BR) locale for .Net BotBuilder

- Node/core/lib/botbuilder.d.ts
> fix IChatConnectorSettings and add IChatConnectorEndpoint definitions in botbuilder.d.ts

- Node/core/src/bots/Library.ts
> [Node SDK] Fix, cxt is undefined

- Node/core/src/bots/UniversalBot.ts
> [feature] add public loadSessionWithoutDispatching function

- CSharp/Samples/AnnotatedSandwichBot/AnnotatedSandwich.cs
Ref = #2780 
This will fix the short-circuit problem for "No Preference" in topping selection.
> [.NET] Code Examples - Proposed fix for #2780.

- CSharp/Library/Microsoft.Bot.Builder/Resource/Resources.pt-BR.resx
Increase option to "yes" and "no" choices for pt-BR
> [.NET SDK] Improve pt-BR choice translation

- Node/core/lib/dialogs/EntityRecognizer.js
- Node/core/src/dialogs/EntityRecognizer.ts
Addresses underlying cause of #3516.
> [Node.js SDK] EntityRecognizer.findAllMatches fix to prevent scores > 1.0 and adjust score generation

- Node/core/lib/bots/ChatConnector.js
- Node/core/src/bots/ChatConnector.ts
* Adds HTTP verb to the error message
> [Node.js SDK] Improve ChatConnector request error text

- CSharp/Samples/AnnotatedSandwichBot/Microsoft.Bot.Sample.AnnotatedSandwichBot.csproj
- CSharp/Samples/NuGet.config
This will ensure packages restore to the correct directory, and update package references for AnnotatedSandwichBot.
> Adds NuGet.config for samples

- Node/core/lib/dialogs/ActionSet.js
- Node/core/src/dialogs/ActionSet.ts
> [Node.js SDK] Fix unique action key

- Node/core/src/bots/ChatConnector.ts
> [Node.js SDK] Update missing service url/address error message to be more detailed

- CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs
Treat null and empty intent handlers. Key variable unused.
(https://github.com/Microsoft/BotBuilder/issues/4140)
> Checking null and whitespaces in intent handlers.

- Node/core/lib/botbuilder.d.ts
> [Node.js SDK] Added missing constructors for UniversalBot (#3261)

- CSharp/Library/Microsoft.Bot.Builder.Autofac/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder.Calling/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder.FormFlow.Json/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder.History/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.nuspec
- CSharp/Library/Microsoft.Bot.Builder/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore/Microsoft.Bot.Connector.AspNetCore.nuspec
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/Microsoft.Bot.Connector.AspNetCore2.nuspec
- CSharp/Library/Microsoft.Bot.Connector.Falcon/Microsoft.Bot.Connector.nuspec
- CSharp/Library/Microsoft.Bot.Connector.Falcon/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.NetCore/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.NetFramework/Microsoft.Bot.Connector.nuspec
- CSharp/Library/Microsoft.Bot.Connector.NetFramework/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs
- CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorClientEx.cs
- CSharp/Library/Microsoft.Bot.Connector.Shared/JwtTokenExtractor.cs
- CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs
- CSharp/Library/Microsoft.Bot.Connector.Shared/StateClientEx.cs
- CSharp/Library/Microsoft.Bot.Connector.Standard/AssemblyInfo.cs
- CSharp/Tests/Microsoft.Bot.Builder.Tests/GetTokenRefreshTests.cs
- CSharp/Tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
* replace instance HttpClient with singleton in Auth path
* Change RefreshToken to have single Task so only 1 request happens even when under load
* change ConnectorClient and StateClient to use singleton httpclient 
* Bump version to 3.14.0
> Fix perf issues with HttpClient in SDK

- Node/examples/basics-localization/app.js
- Node/examples/basics-localization/customLocale/pl/index.json
This updates basics-localization bot with Polish language support in NodeJS samples.
Thanks!
> [Node.js SDK] Add Polish (pl) locale to sample Node.js Bot

- CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
- CSharp/Library/Microsoft.Bot.Builder/MultilingualResources/Microsoft.Bot.Builder.el.xlf
- CSharp/Library/Microsoft.Bot.Builder/Resource/Resources.el.resx
With this pull request, i am adding the files needed for the greek language translations .
> Add greek language translation

- CSharp/Library/Microsoft.Bot.Builder/Dialogs/GetTokenDialog.cs
Fixing a bug in GetTokenDialog
> Fixing a bug in GetTokenDialog

- Node/core/lib/botbuilder.d.ts
- Node/core/lib/bots/ChatConnector.js
- Node/core/lib/cards/OAuthCard.js
- Node/core/src/bots/ChatConnector.ts
- Node/core/src/cards/OAuthCard.ts
- Node/examples/basics-oauth/app.js
A few changes:
1. Added a basic OAuth sample bot
2. Added the api.botframework.com endpoint for the OAuthApi calls
> Final Node support for OAuthCards

- CSharp/EchoBot/Web.config
- CSharp/Library/Microsoft.Bot.Builder.Autofac/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder.Calling/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder.FormFlow.Json/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder.History/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/IConnectorClientFactory.cs
- CSharp/Library/Microsoft.Bot.Builder/Dialogs/GetTokenDialog.cs
- CSharp/Library/Microsoft.Bot.Builder/Dialogs/LuisDialog.cs
- CSharp/Library/Microsoft.Bot.Builder/Microsoft.Bot.Builder.nuspec
- CSharp/Library/Microsoft.Bot.Builder/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore/Microsoft.Bot.Connector.AspNetCore.nuspec
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/Microsoft.Bot.Connector.AspNetCore2.nuspec
- CSharp/Library/Microsoft.Bot.Connector.Falcon/Microsoft.Bot.Connector.nuspec
- CSharp/Library/Microsoft.Bot.Connector.Falcon/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.NetCore/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.NetFramework/Microsoft.Bot.Connector.nuspec
- CSharp/Library/Microsoft.Bot.Connector.NetFramework/Properties/AssemblyInfo.cs
- CSharp/Library/Microsoft.Bot.Connector.Standard/AssemblyInfo.cs
We call back into developers code so we need to maintain the async/await context
> remove configure awaits

- CSharp/Samples/README.md
GraphBot does not exist so this link was a broken link.
> Removed broken link

- CSharp/Samples/AlarmBot/Dialogs/AlarmDispatchDialog.cs
- CSharp/Samples/AlarmBot/Dialogs/AlarmLuisDialog.cs
- CSharp/Samples/AlarmBot/Models/AlarmModule.cs
- CSharp/Samples/AlarmBot/README.md
> C# AlarmBot Sample: mention both AlarmLuisDialog and AlarmDispatchDialog

- Node/Generator/README.md
Removing this unused text until it gets sorted out `[![NPM version][npm-image]][npm-url] [![Build Status][travis-image]][travis-url] [![Dependency Status][daviddm-image]][daviddm-url]`
> Removing unused text from readme

- Common/Transcripts/CoreExtensionsTests/ConversationStateTest.chat
- Common/Transcripts/CoreExtensionsTests/CustomStateTest.chat
- Common/Transcripts/CoreExtensionsTests/UserStateTest.chat
- Common/Transcripts/CoreTests/BotAdapted_Bracketing.chat
- Common/Transcripts/DialogsTests/AttachmentPrompt.chat
- Common/Transcripts/DialogsTests/ChoicePrompt.chat
- Common/Transcripts/DialogsTests/ConfirmPrompt.chat
- Common/Transcripts/DialogsTests/ContentAttachment.json
- Common/Transcripts/DialogsTests/DateTimePrompt.chat
- Common/Transcripts/DialogsTests/NumberPrompt.chat
- Common/Transcripts/DialogsTests/TextPrompt.chat
- Common/Transcripts/DialogsTests/Waterfall.chat
- Common/Transcripts/DialogsTests/WaterfallNested.chat
- Common/Transcripts/DialogsTests/WaterfallPrompt.chat
- Common/Transcripts/LuisTests/LuisMiddleware.chat
- Common/Transcripts/QnATests/QnAMiddleware.chat
- Common/Transcripts/README.md
- Common/Transcripts/TranslationTests/LocaleConvertToEnglish.chat
- Common/Transcripts/TranslationTests/TranslateToEnglish.chat
- Common/Transcripts/TranslationTests/TranslateToUserLanguage.chat
This PR contains the transcript files (.chat files) used in BotBuilder-v4 for testing several components and guarantee the same behavior between the different platform.
> BotBuilder (v4) Transcript files

- README.md
Adding link to personalitychat repo in the botbuilder repo readme.
> Adding reference to personalitychat repo

- Node/core/lib/botbuilder.d.ts
- Node/core/lib/bots/ChatConnector.js
- Node/core/src/bots/ChatConnector.ts
- Node/core/src/interfaces.d.ts
* new getPagedConversationMembers() API
> update schema for node

- README.md
- move v3 SDKs to the end of the table
- promote v4 SDKs higher in the list
> Reorder issues table

- README.md
- updated readme to provide a link for logging issues against ABS portal and various channels
> Add a link to ABS & Channels repo

- README.md
we need a place to list community projects, botkit, adapters, etc.
> add community / extension section

- specs/botframework-protocol/botframework-channel.json
includes changes to AttachmentView wording and the addition of Activity.callerId
> Latest swagger file

- dri/README.md
- dri/report.py
Command line tool to view active/aging issues associated with the Bot Framework Github repos.
Requires Python.
Currently performs the following (for repos managed by the Bot Framework):
- Filters out Microsoft employees or vendors
- Count of  **total issues** after `7/1/1019`.
- Issues that don't contain the **`Bot Services`** label.
- Issues that don't contain the **`customer-reported`** label.
- Issues that don't contain the  **`customer-replied-to`** label.
- Issues that are endanger of not being closed within 90 days.
- Outputs to local console and generates a HTML report.
Install dependent package.
```bash
pip install PyGithub
```
This uses a personal access token to authenticate with Github.
- Go to https://github.com/settings/tokens
- Click on "Generate new token"
- Give note like …
> SDK DRI tool

- README.md
Update the what's new text to a generic text
> Updating 'what's new' text

- specs/botframework-activity/botframework-activity.md
Fixes #5651 out link to manifest.md was incorrect.
> Fixes #5651 - Activity Schema documentation broken link

- dri/report.py
`shikhamishra11` files accessibility bugs for Emulator.
> Filtering out shikhamishra11

- dri/.gitignore
- dri/report.py
cc: @sgellock 
* remove BotFramework-Services from tracked repos
* added @clearab as MS employee
* fix issue opening report on *nix platforms
> Update dri script

- schemas/skills/samples/complex-skillmanifest-2.0.0.json
- schemas/skills/samples/echo-skillmanifest-2.0.0.json
- schemas/skills/samples/simple-skillmanifest-2.0.0.json
- schemas/skills/skill-manifest-2.0.0.json
Fixed some typos in the schema descriptions.
Updated formatting to use default VS Code (4 spaces for tabs) to make it easier to compare difs.
> Fixes typos and formatting in schema descriptions.

- schemas/skills/samples/complex-skillmanifest-2.0.0.json
- schemas/skills/samples/echo-skillmanifest-2.0.0.json
- schemas/skills/samples/simple-skillmanifest-2.0.0.json
Updated schema URL for samples to point to https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json
> Updated schema URLs for Skills Manifests

- README.md
- update 4.7 version where appropriate
- adjust language on the preview features section
> 4.7 update notes

- README.md
- Adds the non-duplicate content from microsoft/botframework
- Adds reference to the new content in the intro
- Fixes what's new link to point to Azure Bot Service what's new (which is actually getting updated by Kamran reliably)
> docs: merge readme from botframework repo

- dri/report.py
Update dri tool to add missing people.
> Add zerryth, stevkan & diberry to filter

- specs/testing/SkillsMatrixTesting.md
MD Spec to formalize our thinking around automating the skills testing matrix. 
Feedback welcome
> Skills testing

- dri/report.py
Mispelled Steve's name.
We can use the opportunity to quickly go through the code in case you need to tweak anything in the future..
> Add stevkan to excludes

- README.md
Updated versions and other text related to the 4.8 release
> 4.8 release

- README.md
Added the C# Adapters into the adapter matrix
> Update Readme with C# Adapter List

- schemas/component/baseComponent.schema
- schemas/component/component.schema
- schemas/component/readme.md
* Move component.schema 
* Move baseComponent.schema 
* add readme.txt
> move component schema to botframework-sdk

- dri/helpers.py
- dri/report.py
Update the DRI report tool to filter out issues explicitly labeled with "ExemptFromDailyDRIReport"
> add a new ExemptFromDailyDRIReport filter

- specs/botframework-activity/botframework-activity.md
https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json
> Fixing broken links.

- schemas/skills/skill-manifest-2.0.0.json
- schemas/skills/skill-manifest-2.1.preview-1.json
Made $schema property required and fixed typo in activities description
> Minor updates to SkillManifest 2.1

- schemas/readme.md
- schemas/skills/readme.md
- schemas/skills/samples/complex-skillmanifest-2.1.preview-1.json
In this PR:
- Add some "other" activities to the complex skill manifest for testing purposes
- add a README to the skills folder
> Skills manifest: Add readme & more complexity to the sample

- schemas/skills/readme.md
- schemas/skills/skill-manifest-2.1.preview-1.json
- schemas/skills/v2.0/skill-manifest.json
- schemas/skills/v2.1/samples/complex-pva-manifest.json
- schemas/skills/v2.1/samples/echo-skillmanifest.json
- schemas/skills/v2.1/samples/simple-skillmanifest.json
- schemas/skills/v2.1/skill-manifest.json
This PR finalizes the skill manifest versioning process that should accommodate and simplify future versions of the manifest, while remaining backwards compatible.
> Finalize skill manifest versioning

- dri/report.py
Adds v-kydela to MS Employee list
> MS Employee update

- specs/botframework-activity/botframework-activity.md
- specs/botframework-protocol/botframework-channel.json
After merging relevant changes on SDK into OBI repo, this PR brings the bf-sdk version at parity with the updated OBI.
> Activity spec and channel swagger updates

- schemas/ui/v1.0/ui.schema
refs #5955 
Adding support for grouping in the menu schema. Supports upcoming designs.
> refactor menu uischema to support grouping

- schemas/ui/v1.0/ui.schema
refs #5960 
Fixes an issue with schema validation by moving sibling keywords into UI schema definition.
> use correct definition of UI Schema

- docs/BF Labeling Guide.md
Added areas for AI-Orchestrator, Engineering and SDK.
Updated Feature request, Technical debt and Team agility to use - as separators
> Labeling doc updates

- .github/ISSUE_TEMPLATE/bot-framework-bug.md
- .github/ISSUE_TEMPLATE/bot-framework-feature-request.md
Updated feature request template to apply new default labels on creation.
Added bug issue template with proper labels.
> Updated issue and PR template

- Orchestrator/v0.1/nlr_versions.json
- Orchestrator/v0.1/nlr_versions.schema
Host nlr_versions in github instead of blob store.
> added nlr_versions.json/schema

- docs/BF Labeling Guide.md
Reviewed label usage with @cleemullins, @tracyboehrer, @mrivera-ms and @munozemilio and removed `approved` and `in-progress` labels.
> Removed approved and in-progress labels and updated references.

- Orchestrator/v0.1/nlr_versions.json
> upgrade to 12-layer ONNX V1.4 model

- README.md
> Update Stable Release entries in readme

- Orchestrator/v0.1/nlr_versions.json
> update nlr_versions.json for new models

- specs/testing/skills/SkillsFunctionalTesting.md
- specs/testing/skills/scenarios/AuthWithOAuthCard.md
- specs/testing/skills/scenarios/AuthWithSSO.md
- specs/testing/skills/scenarios/CardActionsWithInvokes.md
- specs/testing/skills/scenarios/DraftScenarios.md
- specs/testing/skills/scenarios/MultiTurnInteraction.md
- specs/testing/skills/scenarios/ProactiveMessage.md
- specs/testing/skills/scenarios/SingleTurnInteraction.md
- specs/testing/skills/scenarios/SkillCallsSkill.md
- specs/testing/skills/scenarios/SkillReceivesAttachment.md
- specs/testing/skills/scenarios/SkillStartsConversation.md
- specs/testing/skills/scenarios/TeamsAPI.md
- specs/testing/skills/scenarios/TeamsSkillWithTaskModule.md
- specs/testing/skills/scenarios/UpdateDeleteAdaptiveCard.md
Relates to #6025 
Moved each scenario into a separate file to make it easier to handle merges and updates.
> Breaks up scenarios in separate files

- schemas/ui/v1.0/ui.schema
Fixes missing type in fieldset oneOf schema.
> fix: Fixed fieldset oneOf schema

- Orchestrator/README.md
- Orchestrator/docs/BFOrchestratorUsage.md
- Orchestrator/docs/NLRModels.md
> Update sdk orchestrator readme

- Orchestrator/v0.1/nlr_versions.json
Fixes #
Ning’s evaluations show that the 6 layer is the best model as default base model.
- 
-
-
> Update default basemodel in  nlr_versions.json

- Orchestrator/docs/DispatchMigrationExample.md
Added LUIS/QnAMaker export instructions
> Update DispatchMigrationExample.md with LUIS/QnA export instructions

- Orchestrator/README.md
Edit for style and clarity.
Visual review of updated .md content.
> Copy edit of the Orchestrator readme

- Orchestrator/README.md
Fixes https://github.com/microsoft/BotBuilder-Samples/issues/2909
> Switched skills link to latest msdocs skills

- Orchestrator/README.md
> Update limitations section (add EN only)

- Orchestrator/docs/NLRModels.md
- Orchestrator/v0.1/nlr_versions.json
Remove Roberta model from list.
Fixes #
#6161
> Removed RoBERTa model from nlrversions.json and NLRModels documentation

- Orchestrator/v0.2/nlr_versions.json
Fixes #
Changed default section to accommodate multiple defaults per language/type.
> Version 0.2 of nlr_versions

- Orchestrator/docs/NLRModels.md
> add evaluation results to Orchestrator NLRModels.md

- Orchestrator/docs/NLRModels.md
> add multilingual languages

- Orchestrator/docs/NLRModels.md
- Orchestrator/v0.2/nlr_versions.json
> renamed 6-layer models

- schemas/component/component.schema
Fixes https://github.com/microsoft/botframework-sdk/issues/6207
thanks @chrimc62 !
> Add Action Policy definitions to component schema

- schemas/component/component.schema
> component schema main-master

- schemas/component/v1.0/component.schema
> Add policies to v1 component schema

- Orchestrator/docs/NLRModels.md
- Orchestrator/v0.2/nlr_versions.json
> EN entity models and revert 20210211 to 20210205

- Orchestrator/docs/NLRModels.md
- Orchestrator/v0.2/nlr_versions.json
> update entity numbers, remove multilingual entity models

- specs/botframework-activity/botframework-activity.md
Update spec for Command and Command result activities
> Add support for Command and Command result activities

- Orchestrator/docs/Overview.md
> active learning

- Orchestrator/v0.2/nlr_versions.json
> Update nlr_versions.json with aka.ms blob urls

- Orchestrator/docs/Overview.md
Update to reflect latest version.
> Update Overview doc

- Orchestrator/README.md
> Doc: Updated Orchestrator platform requirements

- Orchestrator/docs/FAQ.md
> Orchestrator FAQ

- Orchestrator/docs/BFOrchestratorUsage.md
> Fixed the link to Dispatch Migration

- Orchestrator/README.md
> Doc: alternate orchestrator models in composer.

- README.md
> Fixed SDK linked issue

- Orchestrator/Samples/README.md
Support of how-to documentation for Orchestrator (move from samples/experimental)
Fixes #
- 
-
-
> Placeholder for Orchestrator samples

- Orchestrator/docs/FAQ.md
> use aka.ms for nlrmodels redirect

- Orchestrator/docs/NLRModels.md
- Orchestrator/v0.2/nlr_versions.json
> Trim model list and documentation for R13.

- Orchestrator/v0.2/nlr_versions.json
> remove lingering comma

- Orchestrator/docs/package/README.md
First part in fixing package doc references.
> Orchestrator package readme

- Orchestrator/docs/NLRModels.md
- Orchestrator/v0.2/nlr_versions.json
> update model versions

- .github/CODEOWNERS
Addresses https://github.com/microsoft/botframework-sdk/issues/6401
Added code owners file to the repo that references @microsoft/botframework-sdk
> Adds code owners file to the SDK project

- Orchestrator/README.md
Fixes [Dead Links Additional Reading #6459](https://github.com/microsoft/botframework-sdk/issues/6459)
> Update README.md: Fix Orchestrator C# and NodeJS sample links

- specs/botframework-activity/botframework-activity.md
Fixed broken links for Transcript and Bot Framework Manifest.
Fixes #
Updated link references
> Fixed broken links

- codeql3000.yml
Fixes #minor
Per request: Tracy's email 'RE: Diganta Kumar mentioned you in "2022.11.08 BAP Fundamentals Conversation AI Talking Points".'
Add codeql3000.yml
> Turn on CodeQL for botframework-sdk
