microsoft/botframework-sdk

Node/src/bots/SlackBot.ts
Current implementation fails to replace additional instances of esc. characters.
=> Replace all the instances instead of the first one

CSharp/Library/Dialogs/PromptDialog.cs
When replying to a PromptConfirm, the logic does not properly interpret answers that are not lower-cased.  It is common for smart phones to "autocorrect" response casing so the bug is quite noticeable when interacting with a bot through a smartphone.
=> PromptConfirm TryParse should ignore casing on message

Node/src/Session.ts
This matters on case-sensitive filesystems---that is, it arises on Linux but generally doesn't come up on Windows or OS X. On ext4 and othercase-sensitive filesystems, Node can't find `consts.ts` when it is referenced as `Consts`.
In particular, I got this error when running a bot on Linux:
```
module.js:341
throw err;
^
Error: Cannot find module '../Consts'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> ([snip]/node_modules/botbuilder/lib/dialogs/DialogCollection.js:10:14)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at …
```
=> Fix capitalization in reference to `consts.ts`

Node/src/Message.ts
Nice feature introduced in 0.9.0. Just tested this and got an "undefined" as bot reply. Found this cause.
=> Changed Math.round to Math.floor to fetch random array element

CSharp/Library/FormFlow/FormDialog.cs
Reproduction steps:
- Add a ValidateDelegate performing an asynchronous task to a Form Field Step (an http call in my case)
- Pre-fill the Step with a value
The form dialog will fail to start.
=> Make Form preset entity validation async

CSharp/Samples/PizzaBot/Pizza.cs
It appears the delivery address field is named "Address" in LUIS, but named DeliveryAddress in the PizzaOrder class.  Consequently, LUIS can't initialize the DeliveryAddress property.
=> Pizza DeliveryAddress fix.  Possible fix to issue #149.

CSharp/Library/Dialogs/LuisDialog.cs
I find these two extensibility points useful for my pet project:
1) `GetLuisQueryTextAsync` is useful when you want to do change the message text before passing to LUIS. For instance, you can extend the message with some context information to improve LUIS intent matching etc.
2) `GetHandlersByIntent` is useful if you want to change the way intent handlers are discovered and/or created; for instance, IoC frameworks could be used here.
=> More extensibility points for LuisDialog

Node/lib/bots/BotConnectorBot.js
`res.send(status, body)` is deprecated in expressjs, replaced it with `res.status(status).send(body)`
=> Remove deprecation warning in expressjs

CSharp/Samples/SimpleAlarmBot/SimpleAlarmDialog.cs
Issue #509 . 
The problem was making ILuisService optional and passing null as default value. LuisDialog now accepts params ILuisService[] services which was taking null as first item of the array resulting in NullReferenceException. Refer to my comment on the issue.
Fixed this by adding a default constructor and removed the default null assignment from other constructor.
=> Fixed issue #509.

Node/lib/bots/BotConnectorBot.js
In call to `res.status(200)` response returns statusCode (200) instead of response object (this), so there is no chaining.
=> Fix restify API

Node/core/lib/logger.js, Node/core/src/logger.ts
Example of the output one will get when having `"NODE_DEBUG" : "botbuilder"`
```
ChatConnector: message received.
Message Received:  yeh
..Prompts.text - session.endDialogWithResult()
result: yeh
./address - session.sendBatch() sending 0 messages
{ faulted: true,
success: 0,
errors: [ { request: 'yeh', index: 0, reason: 'Not Found' } ] }
./address - session.send()
./address - session.beginDialog(BotBuilder:Prompts)
..Prompts.text - session.send()
..Prompts.text - session.sendBatch() sending 2 messages
ChatConnector: sending message.
ChatConnector: sending message.
```
or 
```
session.beginDialog(/)
/ - waterfall() step 0 of 11
/ - session.send()
/ - waterfall() step 1 of 11
/ - waterfall() step 2 of 11
/ - waterfall() step 3 of 11
/ - session.send()
/ - session.beginDialog(/address) …
```
=> allow additional logging through NODE_DEBUG #716

Contributing.md
Add a link to the required [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
=> Add code of conduct

CSharp/Library/Microsoft.Bot.Connector/ActivityEx.cs, CSharp/Samples/GraphBot/Microsoft.Bot.Sample.GraphBot/project.fragment.lock.json
ChannelId was not copied when creating replay message. 
Channel Id can be used in dialogs to modify the answer to better use each channel features.
The service URL was also missing.
=> Include ChannelId when creating replay message.

Node/core/src/dialogs/DialogAction.ts
When compiling to typescript, the `ResumeReason.completed` enum evals to `0`
```js
ResumeReason[ResumeReason["completed"] = 0] = "completed";
```
which is a falsy value. Therefore, any waterfall step that users want to mark as `complete` by using the `next|skip` callback, are automatically marked as `forward` 
Fixes #883
=> Undesired forward resume status in waterfall step

Node/examples/demo-skype/app.js
SigninCard does not have a `title` function instead should be `text` according to the latest code
https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.signincard.html
=> Fix Demo Skype Example

CSharp/Documentation/Routing.cs
Changed several things to make the "init conversation" sample work:
- correct userAccount initialization
- correct ConnectorClient initialization with ServiceUrl
- aligned botAccount with other samples on this page
- unified conversationId to camel case
=> Corrections for CreateConversation samples

Node/core/src/bots/ConsoleConnector.ts, Node/core/src/bots/UniversalBot.ts
The callback passed to this function in `Session.sendBatch` is supposed to reset `session.sendingBatch` to `false`, making it available for further messages. However, in two cases, this callback was not called:
1. In `ConsoleConnector.send` it was simply ignored
2. In `UniversalBot.send` it was not called if an error occured
See #1023 for an example where it caused problems.
=> Use the callback passed to Session.options.onSend everywhere

Node/calling/src/CallSession.ts
Changed CallSession.ts to require('./workflow/Prompt') instead of require('./workflow/prompt');
I was trying to deploy my skype calling bot on a PaaS platform on Node 6.3.1. When the app tried to start up, the platform complained with "Error: Cannot find module './workflow/prompt'". 
I changed CallSession.ts import prompt = require('./workflow/prompt') to require('./workflow/Prompt')  and it fixed my problem
=> changed CallSession.ts to require('./workflow/Prompt')

CSharp/Library/Microsoft.Bot.Connector/StateClientEx.cs
https://github.com/Microsoft/BotBuilder/issues/1017
=> StateClient constructor comments fixed.

CSharp/Library/Luis/LuisModel.cs, CSharp/Library/Luis/LuisService.cs, CSharp/Samples/AlarmBot/Models/AlarmModule.cs
See #1160 for discussion on implementation. This change will allow `LuisService`s to be instantiated through any object that implements the new `ILuisModel`, allowing users to more easily load from a config file or dynamically through IoC.
=> Extract LuisModelAttribute variables into interface

CSharp/Library/Dialogs/Address.cs, CSharp/Library/Dialogs/ResumptionCookie.cs
Enable deserialization of an instance of **ResumptionCookie** by adding **JsonConstructorAttribute** to **Address** constructor and adding Address based constructor (JsonConstructor) to **ResumptionCookie**.
=> Fix Deserializing a ResumptionCookie.

CSharp/Library/Microsoft.Bot.Builder.Calling/Models/Contracts/Recognize.cs, CSharp/Library/Microsoft.Bot.Builder.Calling/Models/Contracts/Record.cs, CSharp/Library/Microsoft.Bot.Builder.Calling/Models/Misc/MinValues.cs
This change allows for timeouts that are fractions of a second or are smaller than 1 second in bot calling contracts. The change allows for double timeouts in Recognize and Record action.
=> Make the bot calling timeouts to be doubles instead of uints.

Node/core/lib/bots/ChatConnector.js
How to reproduce
- Build a bot with 'botbuilder' and 'express'
- Send a request without body
- Server down
Sample bot code:
```javascript
const express = require('express');
const builder = require('botbuilder');
const app = express();
app.get('/', function(req, resp) {
resp.send('Hello world');
});
const port = process.env.port || 3000;
app.listen(port, function(){
console.log(`Listening on port ${port}`);
});
var connector = new builder.ChatConnector({
appId: process.env.MICROSOFT_APP_ID,
appPassword: process.env.MICROSOFT_APP_PASSWORD
});
var bot = new builder.UniversalBot(connector);
app.post('/api/messages', connector.listen());
bot.dialog('/', function(session) {
session.send("Hello World");
});
```
Sample request:
`% curl -X POST http://localhost:3978/api/messages`
```
Stack trace …
```
=> Prevent from server down if request body has nothing

Node/core/src/botbuilder.d.ts
The current implementation [makes a guard over not defining the `resumed` property](https://github.com/Microsoft/BotBuilder/blob/e8c5aaaa273f6265fd983e5ded2f3b147a9867b6/Node/core/src/Session.ts#L297-L299), so it should be optional in TS to avoid generating verbose code
before
```ts
session.endDialogWithResult({
resumed: BotBuilder.ResumeReason.completed,
response: true
});
```
after
```ts
session.endDialogWithResult({
response: true
});
```
=> [Node] Definitions for IDialogResult.resumed

en-us/node/builder/chat/IntentDialog.md
At [node's IntentDialog page](https://docs.botframework.com/en-us/node/builder/chat/IntentDialog), the link to class reference [DialogAction](https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.dialogaction.html) and [IIntentRecognizer](https://docs.botframework.com/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentrecognizer.html) were broken.
=> Update IntentDialog.md, fix broken links

Node/core/lib/botbuilder.d.ts
`IDialogResult<T>` interface has a template syntax, so `endDialogWithResult` which takes that interface as argument, should propagate the template
=> [Node] Propagate types in endDialogWithResult

Node/core/src/bots/ConsoleConnector.ts
Fixes #1570
The ConsoleConnector is declaring the same variable `i` in two nested loops, which mades the inner loop to modify the value of the outer loop index.
Some of the consequences of this bug are described in #1570.
This could be solved using `let` instead of `var` but I've seen that you are not using `let` in the framework, so I've renamed the inner loop index from `i` to `j`.
=> Fix loop indexes are being meshed up in the ConsoleConnector

Node/core/src/dialogs/EntityRecognizer.ts
Fixes #1846 
Reg exps for `yesExp` and `noExp` don't end with `$` which is fine to match "yes, please" responses, but it mades "yesterday" to be also recognized as an affirmative response.
Ending the reg exp with `(\W|$)` allows it to match "yes", "yes, please" but not "yesterday".
=> Fix EntityRecognizer is very relaxed when parsing affirmative/negative responses

CSharp/Library/Microsoft.Bot.Builder/MultilingualResources/Microsoft.Bot.Builder.fa.xlf, CSharp/Library/Microsoft.Bot.Builder/Resource/Resources.fa.resx
Hi Microsoft Developers
I am a Persian .Net developer. I have started to use Microsoft Bot Framework for developing a Telegram Bot.
It seems Persian resource has been translated by machine not human so I try to fix them. There are some mistakes and funny translations.
=> Fixing persian resources.

CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs, CSharp/Tests/Microsoft.Bot.Builder.Tests/PromptTests.cs
This address the issue #1810. Now the code will be executed every time the property is called.
=> Update PromptConfirm's Options and Patterns getter

Node/core/lib/dialogs/PromptChoice.js, Node/core/src/dialogs/PromptChoice.ts
When dealing with reverse ordinals, the `match.entity` will be a negative value and so it needs to be subtracted from the `choices.length` to get the proper index. The current code is adding the `match.entity` value because its doing minus negative number.
=> Fix index when dealing with reverse ordinals

CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/Activity.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/AnimationCard.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/AudioCard.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/HeroCard.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/ReceiptCard.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/SigninCard.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/ThumbnailCard.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/Models/VideoCard.cs
Collections off our activity and card objects should be able to have `.Add()` run on them readily; today they default to `null` values which causes a first-time-crash almost without fail for developers getting to learn our API.
=> No null collections

CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptRecognizer.cs, CSharp/Tests/Microsoft.Bot.Builder.Tests/PromptTests.cs
Options matching was failing in a PromptChoice like the following:
```
var severities = new string[] { "High", "Normal", "Low" };
PromptDialog.Choice(context, this.SeverityMessageReceivedAsync, severities, "Choose the severity");
```
due to missing case insensitive match. The user message is being converted to lower case, however, the option was maintaining the original case. This PR fix this by converting the option to lower case too.
=> Fix PromptChoice case insensitive issue when matching options

CSharp/Documentation/Dialogs.cs
Noticed that there was a discrepancy between the included code and the sentence below it.
=> [Docs > C#] Bringing Dialog documentation in sync with code

Node/core/lib/dialogs/EntityRecognizer.js, Node/core/lib/locale/de/BotBuilder.json, Node/core/lib/locale/en/BotBuilder.json, Node/core/lib/locale/es/BotBuilder.json, Node/core/lib/locale/fr/BotBuilder.json, Node/core/lib/locale/it/BotBuilder.json, Node/core/lib/locale/pt/BotBuilder.json, Node/core/lib/locale/zh-Hans/BotBuilder.json, Node/core/src/dialogs/EntityRecognizer.ts
Method now checks `locale/<language>/BotBuilder.json` for `"yesExp"` and `"noExp"` before parsing utterance. 
Referencing issue #1813
=> [Node SDK] Add localization to EntityRecognizer.parseBoolean()

Node/core/package.json
**Uninitialized Memory Exposure**
_Medium severity_
Vulnerable module: concat-stream
Introduced through: concat-stream@1.4.10
**Detailed paths**
Introduced through: base64url@1.0.6 › concat-stream@1.4.10
**Overview**
`concat-stream` is writable stream that concatenates strings or binary data and calls a callback with the result. Affected versions of the package are vulnerable to Uninitialized Memory Exposure.
A possible memory disclosure vulnerability exists when a value of type number is provided to the `stringConcat()` method and results in concatenation of uninitialized memory to the stream collection.
This is a result of unobstructed use of the Buffer constructor, whose [insecure default constructor increases the odds of memory leakage.](https://snyk.io/blog/exploiting-buffer/) …
=> [Node SDK] Fix vulnerability in module base64url@1.0.6

Node/examples/README.md
Updating documentation to include building core which is required to run any of the examples.
Otherwise, you get:
Error: Cannot find module 'url-join'
=> [Node SDK] Update README.md

Node/calling/src/botbuilder.d.ts
Compare bots/CallConnector.ts:54
=> [Node SDK] Fix public ICallConnectorSettings callbackUrl naming

Node/core/src/dialogs/ActionSet.ts
It should be possible to invoke the callback without an error, hence the signature change.
I went for the `err: Error | null` signature because:
- it's called with `null` in [some examples](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/feature-onFindAction/app.js#L33)
- it mimics nodejs's stdlib behaviour
(I guess the alternative could have been `err?: Error`, copying the `ErrorCallback` signature of the `async` library used elsewhere in the code, or `err?: Error | null`, merging the two possibilities.)
In any case, I did not change [how the error is handled](https://github.com/Microsoft/BotBuilder/blob/2826c4757be5488ecc13926ecdf540254bf9715d/Node/core/src/dialogs/ActionSet.ts#L182) to make it only check for `err !== null`, as it would be a breaking change.
=> [Node SDK] Fix type signature

Node/core/lib/locale/zh-Hans/BotBuilder.json
Make BotBuilder recognize Chinese characters for boolean expressions correctly.
Referencing issue #2778
=> [Node SDK] Fixed Chinese localization regex patterns

Node/calling/lib/bots/CallConnector.js, Node/calling/src/bots/CallConnector.ts
This PR removes the duplicate JWT verification and relies solely on the implementation in `jsonwebtoken` using the already existing `jwtVerifyOptions`
I also added a call to `console.error` when the connector encounters a token error, in order to provide feedback for otherwise mysterious hangups.
CallConnector.js was built using tsc 2.3.2
=> [Node SDK] remove duplicate jwt check. fix for #2561

Node/calling/src/bots/CallConnector.ts
Fixed typo.
please fix [Documentation](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-manage-conversation) page too 😉
=> Fixed typo in CallConnector

CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs
Fix for: https://github.com/Microsoft/BotBuilder/issues/2932
=> [.NET SDK] Make classes not sealed in PromptDoalog.cs #2932

Node/core/lib/dialogs/Prompt.js, Node/core/src/dialogs/Prompt.ts
Fix Prompt dialog that cannot be interrupted by global action with LUIS intent.
Referencing issue #2839
=> [Node SDK] Fix Prompt IIntentRecognizerResult

Node/core/lib/bots/ConsoleConnector.js, Node/core/src/bots/ConsoleConnector.ts
At the moment the only events that can be processed with the
ConsoleConnector are messages with very restricted configuration. By
adding a processEvent method any event can be tested including messages
with custom sourceEvent setups for real client dependent (Slack, MS
Teams, etc) tests.
=> Add processEvent to ConsoleConnector

Node/core/lib/dialogs/LuisRecognizer.js, Node/core/src/dialogs/LuisRecognizer.ts
Handle LUIS HTTP errors, so the bot can know that anything went wrong. For example if the URL has `http` protocol instead of `https`, the bot gets a 404, if the subscription key is wrong, the bot gets a 401, but in both cases, it thinks that everything went ok, with a result `{ score: 0, intent: null, intents: [], entities: [] }`
=> [Node] Handle LUIS HTTP errors

CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs, CSharp/Tests/Microsoft.Bot.Builder.Tests/PromptTests.cs
@msft-shahins FYI
Related to https://stackoverflow.com/questions/44241355/botframework-promptdialog-choice-no-longer-returns-partial-matches
=> [C# SDK] Allow partial matches when recognizing choices in a PromptChoice

CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs
The docs of the parameters were mixed up.
=> [C# SDK] Fix PromptChoice's recognize* parameters documentation

CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormDialog.cs
Fix NullReference introduced in 3.8.5 when starting FormFlow with FormOptions.PromptInStart.
Fixes the following issues:
- https://github.com/Microsoft/BotBuilder/issues/3157
- https://github.com/Microsoft/BotBuilder/issues/3159
- https://github.com/Microsoft/BotBuilder/issues/3153
=> Fix NullReference when starting FormFlow with FormOptions.PromptInStart

CSharp/Library/Microsoft.Bot.Builder/Luis/Models/EntityRecommendation.cs
This PR is intended to fix issue #2764. 
FYI @msft-shahins @chrimc62
=> [.NET SDK] Add JSONConverter to support builtin.datetimeV2.* LUIS entities

CSharp/Library/Microsoft.Bot.Connector.NetFramework/BotAuthentication.cs
Handle empty string value openIdConfigurationUrl from settings the same way we handle null.
=> skip empty string for  openIdConfigurationUrl

Node/core/lib/dialogs/RegExpRecognizer.js, Node/core/src/dialogs/RegExpRecognizer.ts
Calling exec on a `RegExp` object returns null every second time for matches
which makes recognizer fail every second time if the RegExps are specified as literals
```
bot.recognizer(new RegExpRecognizer('...', {
'*': /.../,
});
```
This prevents that by creating a new RegExp object every time for exec
=> [Node SDK] create new object for exec in RegExpRecognizer

Node/core/lib/bots/UniversalBot.js, Node/core/src/bots/UniversalBot.ts
Addresses #3508, which arose from #3396
=> [Node.js SDK] fix bot.loadSession to use dispatch by default

CSharp/Library/Microsoft.Bot.Builder.Autofac/Properties/AssemblyInfo.cs, CSharp/Library/Microsoft.Bot.Builder/Properties/AssemblyInfo.cs, CSharp/Library/Microsoft.Bot.Connector.NetFramework/Properties/AssemblyInfo.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/JwtConfig.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/JwtTokenExtractor.cs, Node/core/lib/bots/ChatConnector.js, Node/core/lib/bots/Library.js, Node/core/lib/deprecated/LegacyPrompts.js, Node/core/lib/dialogs/EntityRecognizer.js, Node/core/lib/dialogs/PromptRecognizers.js, Node/core/package.json, Node/core/src/bots/ChatConnector.ts
This auth change supports the future move from an independent AAD tenant to the Microsoft Services tenant. This will result in new issuer values being sent and returned, primarily from the emulator code paths. As part of this change, the bot builder version numbers were normalized to 3.10.5.
=> Support for Bot Framework Auth v3.2

CSharp/Samples/AlarmBot/Global.asax.cs, CSharp/Samples/AnnotatedSandwichBot/Global.asax.cs, CSharp/Samples/EchoBot/Global.asax.cs, CSharp/Samples/PizzaBot/Global.asax.cs, CSharp/Samples/SimpleAlarmBot/Global.asax.cs, CSharp/Samples/SimpleDispatchDialog/Global.asax.cs, CSharp/Samples/SimpleEchoBot/Global.asax.cs, CSharp/Samples/SimpleFacebookAuthBot/Global.asax.cs, CSharp/Samples/SimpleIVRBot/Global.asax.cs, CSharp/Samples/SimpleSandwichBot/Global.asax.cs, CSharp/Samples/TemplateBot/Global.asax.cs
InMemoryDataStore name was incorrect, and also there was a mix in autofact patterns for the samples that used Conversation.UpdateContainer().
=> Fix bugs in comments in C# SDK samples. 

CSharp/Library/Microsoft.Bot.Builder/Luis/LuisService.cs
After update to Bot.Builder 3.8.2:
If you create Luis Service this way:
`new LuisService(new LuisModelAttribute("id","key") { Verbose = true})`
your uri to luis won't take Verbose into account, and your url will be like:
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/x?subscription-key=y&q=query&log=True
instead of:
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/x?subscription-key=y&verbose=true&q=query&log=True
Issue #3033
=> [.NET] Properties set for ILuisModel are not taken into account

CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs
This method causes a lot of confusion for people using custom state clients.
=> [.NET SDK] Update ActivityEx.cs mark GetStateClient() as Deprecated

CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/BotAuthentication.cs, CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/BotAuthenticationHandler.cs, CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/BotAuthenticationOptions.cs, CSharp/Library/Microsoft.Bot.Connector.AspNetCore2/Microsoft.Bot.Connector.AspNetCore2.csproj, CSharp/Microsoft.Bot.Builder.sln, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/Controllers/MessagesController.cs, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/Microsoft.Bot.Sample.AspNetCore2.Echo.csproj, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/Program.cs, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/Properties/launchSettings.json, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/Startup.cs, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/appsettings.Development.json, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/appsettings.json, CSharp/Samples/Microsoft.Bot.Sample.AspNetCore2.Echo/wwwroot/default.html
This change adds implementation of BotAuthenticationHanlder based on asp net core 2.0 authentication middleware: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x
The implementation is added in a separate Microsoft.Bot.Connector.AspNetCore2 project to enable making connector nuget support both asp net core 1.x and 2.x authentication model.
=> Add bot authentication support for asp net core 2 authentication middleware

Node/core/lib/bots/ChatConnector.js, Node/core/src/bots/ChatConnector.ts
When using express or restify, in order to get the following handler to
execute, next function needs to be called.
=> [Node.js SDK] Add next() and missing end() calls to ChatConnector

Node/core/lib/botbuilder.d.ts
I'm adding the `processEvent` signature that is missing from a previous PR I did. I removed a lot of whitespaces from the definition file too. But the only real change is the addition of `processEvent(event: IEvent): ConsoleConnector;` to the `ConsoleConnector` class.
CC: @Stevenic
=> Add missing processEvent method to definitions file

CSharp/Library/Microsoft.Bot.Builder.History/ReplayTranscript.cs
ReplayTranscript constructor ignores the "header" argument, because it does not assign the argument to the corresponding field, and it uses the default "header" function.
=> [.NET SDK] ReplayTranscript constructor ignores the "header" argument

CSharp/Library/Microsoft.Bot.Builder/Luis/LuisModel.cs, CSharp/Library/Microsoft.Bot.Builder/Luis/LuisOptions.cs, CSharp/Library/Microsoft.Bot.Builder/Luis/LuisService.cs
Per LUIS Runtime Swagger File, [Line #78](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/cognitiveservices/data-plane/LUIS/Runtime/v2.0/LUIS-Runtime.json#L78)
```js
{
"name": "bing-spell-check-subscription-key",
"in": "query",
"description": "The subscription key to use when enabling bing spell check",
"type": "string"
}
```
=> [.NET SDK] Add support for BingSpellCheckSubscriptionKey to LuisOptions, LuisSevice, LuisModel

CSharp/Library/Microsoft.Bot.Builder.FormFlow.Json/FormBuilderJson.cs, CSharp/Library/Microsoft.Bot.Builder/FormFlow/Attributes.cs, CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormBuilder.cs
IgnoreField attribute for convenient and quick exclusion of extra fields from the class when using FormFlow
=> [.NET SDK] Adding the IgnoreField attribute to the FormFlow #3845

CSharp/Library/Microsoft.Bot.Builder/Dialogs/DialogTaskManager.cs
Fixed `NullReferenceException` when accessing `DialogTaskManager.DialogTasks` if forgot to call `LoadDialogTasks()` first. It's better to provide a meaningful `InvalidOperationException` when accessing this property and it is null
Came across this issue when trying to resolve a new instance of `DialogContext` with Autofac container using a nested lifetime scope. This triggers resolving an `IDialogStack`, which has this registration in `DialogModule.cs` at [this line](https://github.com/Microsoft/BotBuilder/blob/31048a2173313c81a2db47efce6a8a869b4ec284/CSharp/Library/Microsoft.Bot.Builder.Autofac/Dialogs/DialogModule.cs#L223):
`            builder.Register(c => c.Resolve<IDialogTaskManager>().DialogTasks[0])`
If `DialogTaskManager` is instantitated for the first time in current lifetime …
=> DialogTasks: fix NullReferenceException

CSharp/Library/Microsoft.Bot.Builder/MultilingualResources/Microsoft.Bot.Builder.de-DE.xlf
I tried to make the translation sound a bit more natural, so they might differ from those proposed by the machines.
I had some trouble with 
- NumberOrdinals
- BooleanChoices
Does any item in the translated string must have a corresponding item in the original string?
Example:
<trans-unit id="BooleanChoices" translate="yes" xml:space="preserve">
<source>true=y,yes,yep,sure,ok,\u1f44d,\u1f44c|false=n,no,nope,\u1f44e,\\u270b,\\u1f590</source>
<target state="needs-review-translation" state-qualifier="mt-suggestion">True=y,ja,jupp,sicher,ok\u1f44d,\u1f44c|false=n,Nein,Nein,\u1f44e,\\u270b,\\u1f590</target>
</trans-unit>
This would mean y->y, yes->ja, yep->jupp, sure->sicher, ok->ok
Can there be more items in the German translation than in the English translation?
Also are these strings …
=> Manually translated entries from English to German, issue #4219

CSharp/Library/Microsoft.Bot.Connector.NetCore/Content/Microsoft.Bot.Connector.NetCore.XML, CSharp/Library/Microsoft.Bot.Connector.NetFramework/Content/Microsoft.Bot.Connector.xml, CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorAPI/AttachmentsExtensions.cs, CSharp/Library/Microsoft.Bot.Connector.Shared/IActivity.cs
Attachments API test cases were failing because AttachmentsExtension was throwing unseekable stream.
Also, fixing a typo in a /// comment block (which is included in 2 other auto-generated files).
=> Fix for unseekable stream + typo fix

CSharp/Library/Microsoft.Bot.Builder/FormFlow/FormBuilder.cs
fix for: https://github.com/Microsoft/BotBuilder/issues/4344
=> Enumerate missing resources when throwing MissingManifestResourceException

README.md
The current README reads as if this is the v4 repo by mentioning it first. I've received feedback (and agree) its confusing to developers who first access it. 
I moved the line regarding the v4 sdk being in preview to under the v4 heading. In addition I removed the duplicate line 'program in your favorite language' from the intro section as we already have information about it under the v4 heading.
=> Moved v4 sdk line to v4 section as to make readme less confusing

CSharp/Library/Microsoft.Bot.Builder/FormFlow/MessageActivityHelper.cs, CSharp/Library/Microsoft.Bot.Builder/FormFlow/Recognize.cs, CSharp/Library/Microsoft.Bot.Builder/MultilingualResources/Microsoft.Bot.Builder.el.xlf, CSharp/Library/Microsoft.Bot.Builder/Resource/Resources.el.resx
This pull request is making form flow term matching to be accent insensitive. Since now term matching was case insensitive but that was not enough for languages that make use of accents (like Greek lang). As an example καλημέρα is a different term from καλημερα. By removing diacritics from the terms we can easily match both.
The code that is doing the actual work of removing diacritics from words, was found on [John Otander’s blog ](http://www.levibotelho.com/development/c-remove-diacritics-accents-from-a-string)
=> Accent insensitive terms

CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs
Add  `PromptDialog.Text` that accepts `IPromptOptions`.  This is important because on the Cortana channel you cannot have cortana speak the prompt currently.  This is available on other prompts, but not `PromptDialog.Text`.  [There was already a `PromptString` constructor for this](https://github.com/Microsoft/BotBuilder/blob/54d4cf56ef9881d6d8240bb8254c83f427924e6a/CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs#L682).  In the Node Sdk this is already possible out of the box.  In .Net we would have to inherit from `PromptDialog` like this:
```cs
public class PromptDialogTextSpeak:PromptDialog
{
public static void Text(IDialogContext context, ResumeAfter<string> resume, IPromptOptions<string> promptOptions)
{
var child = new PromptString(promptOptions); …
```
=> Update PromptDialog.cs 

Node/core/lib/botbuilder.d.ts
This typographical error prevents the use of the ICardAction literal instead of using the builder on TypeScript
=> Typo fix in ICardAction

CSharp/Directory.Build.props
This reverts commit e22a58e51ed37b071ca8736086dc1bade366037b.
When I merged that commit, it broke versioning for the botbuilder-v3-dotnet-daily packages. So reverting it.
Versioning is controlled by altering the value of the variable VersionRoot in the builds.
=> Revert "Directory.Build.props removed. (#4856)"

CSharp/Library/Microsoft.Bot.Connector.Shared/MicrosoftAppCredentials.cs
HttpResponseMessage implements IDispose, which internally calls .Dispose() on the HttpContent passed into PostAsync(), invalidating the content that was attempted to be reusued in another request.
This fix creates a new Content to be submitted on every attempt by moving the FormUrlEncodedContent inside the retry loop
=> fix objectDisposed exception in RefreshTokenAsync()

specs/botframework-activity/botframework-activity.md
Adding a localTimezone to supplement that localTimestamp. This should be backward-compatible and optional
=> adding localTimezone to spec

README.md
Previous link directed to license file for vscode. Fixed it.
=> Fix link for license file

README.md, specs/botframework-activity/botframework-activity.md, specs/botframework-activity/botframework-cards.md, specs/manifest/botframework-manifest.md, specs/transcript/transcript.md
There were several typos in the documentation that I have fixed in this PR
=> Fix typo on several documentation files

specs/botframework-activity/botframework-activity.md
Thanks @dandriscoll for the clarification on `title` and `image` today. I added the information to the `messageBack` spec. I also fixed the numbering issue for further clarity.
=> Add number fixes & details to messageBack specs

README.md
There was repeated text in our readme pertaining to the CLA and open source code of conduct.  I removed it, so now there is only one copy of this text.
=> Remove repeated text from readme

specs/botframework-activity/botframework-cards.md
Updates two broken links in the Buttons section of the botframework-cards.md file.
Address issue [#81](https://github.com/microsoft/BotFramework-Services/issues/81) on the BotFramework-Services repo.
=> Updates broken links in Buttons section

README.md
Updated spelling of Cortana on the Readme.
=> Typo / Cortana not Cortona

dri/README.md, dri/requirements.txt
Change to use `requirements.txt` to handle dependencies not handled in PyGithub.
=> Add requirements.txt

dri/report.py
Found a couple of folks we should manually ignore in our DRI loop on 2019/12/16
- Adds yochay and ryanlengel to manual MSFT list
=> fix: add yochay and ryan to manual msft list

specs/botframework-protocol/botframework-channel.json
Related: https://github.com/microsoft/botbuilder-dotnet/pull/3054
=> Deprecate Payments

schemas/skills/v2.0/samples/complex-skillmanifest.json, schemas/skills/v2.0/samples/echo-skillmanifest.json, schemas/skills/v2.0/samples/simple-skillmanifest.json
Relates to https://github.com/microsoft/botframework-solutions/issues/3456
Updates the v2.0 sample manifests to point to the version that is in the v2.0 folder and not the backward compat one at the root
=> Updates v2.0 samples to use the /v{version}/ copy of the manifest

schemas/component/component.schema, schemas/component/definitions.schema, schemas/component/v1.0/component.schema
Fixes microsoft/botbuilder-dotnet#3839
Composer uses `$role:expression` to determine if a particular property should be rendered with an expression editor UI control. At the moment certain properties that carry `$ref:schema#/definitions/expression` as well as `$ref:schema:#/definitions/equalsExpression` are not rendered as expression controls in composer UI. 
This PR updates the component schema to add the missing `$role: expression` to the definitions.
=> Update component schema to add $role expression to `expression` and `equalsExpression` definitions

specs/botframework-activity/botframework-activity.md
Fixed the broken link to the Bot Framework Manifest Spec in the References section
Fixes #
- 
-
-
=> broken link fix

schemas/ui/v1.0/ui.schema
Fixes https://github.com/microsoft/BotFramework-Composer/issues/4186
In R10, we introduced Intellisense to Composer fields.
For this first release, the mappings between components and valid Intellisense scopes* were hardcoded.
_*Scopes refer to the type of results that Intellisense returns, such as "user-variables"._
In R11, we would like to have the uiSchema dictates this mapping.
Below is a screenshot of how overwriting the uiSchema enables custom Intellisense scopes.
=> Adding intellisense to uiSchema

schemas/ui/v1.0/ui.schema
Follows #5955 
In #5955, we've checked in the basic ui.schema definition to support customization of Composer's 'form' schema;
based on previous work, this PR appends the 'flow' part to ui.schema definition to support customization of Composer 'flow' schema.
Refs the PR to update botbuilder uischema files: https://github.com/microsoft/botbuilder-dotnet/pull/5099
Here is flow schema's [Typescript definition](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/extension-client/src/types/flowSchema.ts).
The only limitaion of flow schema is, it should have a `widget` property which points to a React component name and be rendered as UI elements finally.
Below is an example of the `flow` schema of `Microsoft.EditArray`:
```
{
"$schema": …
```
=> Add flow uischema definitions in ui.schema

schemas/ui/v1.0/ui.schema
Follows #5955 
Follows #6163
In #5955, we checked in the basic ui.schema definition to support customization of Composer's 'form' schema;
In #6164, we checked in the 'flow' part to ui.schema definition to support customization of Composer 'flow' schema.
As a follow-up of previous work, this PR appends two extra parts 'trigger' and 'recognizer' to ui.schema definition, it will support the customization of Composer Triggers and Recognizers by using uischema.
References the PR in dotnet runtime repo for updating *.uischema files: https://github.com/microsoft/botbuilder-dotnet/pull/5160
**Changes**
Take `Microsoft.OnMessageActivity` as an example:
```js
{
"$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
"form": {...},
"trigger": {
"label": "Message received (Message …
```
=> Add trigger and recognizer uischema definitions in ui.schema

Orchestrator/v0.2/nlr_versions.json
Update Base Model description to reflect the Bot Framework SDK version when it was created.
=> Update basemodel to 4.12 (from 4.10) for new models

Orchestrator/README.md, Orchestrator/docs/BFOrchestratorReport.md, Orchestrator/docs/BFOrchestratorUsage.md, Orchestrator/docs/DispatchMigrationExample.md, parsers/LU/JS/packages/lu/package.json
Remove separate bf orchestrator plugin install instruction and updated links to Orchestrator cli (beta -> main)
Fixes # 6261
=> Removed bf orchestrator plugin instruction since it's no longer a separate bf cli plugin

docs/umlDiagrams/Authentication/ChannelToBot/README.md
Fixes #6277
Fixed typo. "activites" --> "activities"
=> Fixed activities typo in README

.gitignore, schemas/skills/SchemaManifestTests/SchemaManifestTests.csproj, schemas/skills/SchemaManifestTests/SchemaManifestTests.sln, schemas/skills/SchemaManifestTests/ValidateSchemaTests.cs, schemas/skills/v2.1/skill-manifest.json, schemas/skills/v2.2/skill-manifest.json
Failures:
Example failure:
(schema: "2._1.skill-manifest.json", manifest: "2._1.Samples.complex-pva-manifest.json") 
Failure Collection: 
```
[AdditionalPropertiesNotValid: #/activities.bookFlight 
{   NotOneOf: #/activities.bookFlight   {   }   {   }   
{     NoAdditionalPropertiesAllowed: #/activities.bookFlight.name   }   
{     PatternMismatch: #/activities.bookFlight.type   }    } ,
AdditionalPropertiesNotValid: #/activities.getWeather 
{   NotOneOf: #/activities.getWeather   {   }   {   }   
{     NoAdditionalPropertiesAllowed: #/activities.getWeather.name   }   
{     PatternMismatch: #/activities.getWeather.type   }    } ,
AdditionalPropertiesNotValid: #/activities.typing 
{   NotOneOf: #/activities.typing   {     PropertyRequired: #/activities.typing.name   }   
{ …
```
=> Add validation for skill manifest examples against skill manifest schemas

Orchestrator/Samples/dotnet/nlp-with-entities/README.md
Update Orchestrator support for MacOS 10.14 to 10.15 (not supported anymore).
=> Update Orchestrator support for MacOS 10.14 to 10.15

README.md
The link to the webchat docs folder was incorrect and returning a 404 error.
Update the link to the correct location.
=> 404 error for webchat docs link
